[package]
name = "gimic"
version = "0.1.0"
edition = "2021"
license="MIT"
description="The solution for maintain foreing directories/files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
